version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: "@relaycorp/relaynet-core"
    versions:
    - 1.42.10
    - 1.43.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@relaycorp/shared-config"
    versions:
    - 1.4.12
